In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
df = pd.read_csv('final_df.csv')

In [13]:
df.head()

,Unnamed: 0,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0,1565936973,Central Auditory Processing Disorders: New Per...,Gail D. Chermak,1997,Singular Publishing Group Inc,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,136139.0,7.0
1,1,0440200563,Fine Things,Danielle Steel,1988,Dell,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,242143.0,0.0
2,2,0684861593,Amy and Isabelle,Elizabeth Strout,0,Simon Schuster Trade,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,151537.0,0.0
3,3,1891620487,American Greats,Robert A. Wilson,1999,PublicAffairs,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,231237.0,10.0
4,4,2877302962,Bleu presque transparent,RyÃ?Â» Murakami,1999,Philippe Picquier,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,33943.0,0.0

In [14]:
df = df.drop_duplicates(subset=['Book-Title']).reset_index(drop= False)
df

,index,Unnamed: 0,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0,0,1565936973,Central Auditory Processing Disorders: New Per...,Gail D. Chermak,1997,Singular Publishing Group Inc,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,http://images.amazon.com/images/P/1565936973.0...,136139.0,7.0
1,1,1,0440200563,Fine Things,Danielle Steel,1988,Dell,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,http://images.amazon.com/images/P/0440200563.0...,242143.0,0.0
2,2,2,0684861593,Amy and Isabelle,Elizabeth Strout,0,Simon Schuster Trade,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,http://images.amazon.com/images/P/0684861593.0...,151537.0,0.0
3,3,3,1891620487,American Greats,Robert A. Wilson,1999,PublicAffairs,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,http://images.amazon.com/images/P/1891620487.0...,231237.0,10.0
4,4,4,2877302962,Bleu presque transparent,RyÃ?Â» Murakami,1999,Philippe Picquier,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,http://images.amazon.com/images/P/2877302962.0...,33943.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15243,19990,19990,0385490488,Winona's Web,PRISCILLA COGAN,1997,Main Street Books,http://images.amazon.com/images/P/0385490488.0...,http://images.amazon.com/images/P/0385490488.0...,http://images.amazon.com/images/P/0385490488.0...,257554.0,0.0
15244,19991,19991,0060538783,Legendary Warrior,Donna Fletcher,2004,Avon,http://images.amazon.com/images/P/0060538783.0...,http://images.amazon.com/images/P/0060538783.0...,http://images.amazon.com/images/P/0060538783.0...,98391.0,10.0
15245,19992,19992,0140017151,The Flame Trees of Thika: Memories of an Afric...,Elspeth Joscelin Grant Huxley,1981,Penguin Books,http://images.amazon.com/images/P/0140017151.0...,http://images.amazon.com/images/P/0140017151.0...,http://images.amazon.com/images/P/0140017151.0...,882.0,0.0
15246,19994,19994,0743234359,American Jihad: The Terrorists Living Among Us,Steven Emerson,2003,Free Press,http://images.amazon.com/images/P/0743234359.0...,http://images.amazon.com/images/P/0743234359.0...,http://images.amazon.com/images/P/0743234359.0...,253106.0,0.0
15247,19997,19997,0747264929,LOOKING BACK,Josephine Cox,2001,Headline,http://images.amazon.com/images/P/0747264929.0...,http://images.amazon.com/images/P/0747264929.0...,http://images.amazon.com/images/P/0747264929.0...,157247.0,6.0

In [15]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['Book-Title'])

In [17]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(15248, 15003))

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
def search_based_recommendation(book_title,df,tfidf,tfidf_matrix,n=10):
    query_vector = tfidf.transform([book_title])
    cosin_sim  = cosine_similarity(query_vector,tfidf_matrix).flatten()
    sim_scores = list(enumerate(cosin_sim))
    sim_scores = sorted(sim_scores,key=lambda x:x[1],reverse=True)
    sim_scores = sim_scores[1:n+1]
    book_indices = [i[0] for i in sim_scores]
    return df[['Book-Title','Book-Rating','Image-URL-M']].iloc[book_indices].reset_index(drop=True)

In [23]:
df[['Book-Title','Book-Rating']].iloc[4]

Book-Title     Bleu presque transparent
Book-Rating                         0.0
Name: 4, dtype: object

In [31]:
book_to_search = "The Fountainhead"
recommend_books = search_based_recommendation(book_to_search,df,tfidf,tfidf_matrix)
recommend_books

,Book-Title,Book-Rating,Image-URL-M
0,The Novel,0.0,http://images.amazon.com/images/P/0449221431.0...
1,"The Sun, the Moon, and the Stars",0.0,http://images.amazon.com/images/P/0441790992.0...
2,"The Return of the King (The Lord of the Rings,...",7.0,http://images.amazon.com/images/P/0345339738.0...
3,The Sisterhood: The True Story of the Women Wh...,0.0,http://images.amazon.com/images/P/0671495534.0...
4,The Book of the Lion,0.0,http://images.amazon.com/images/P/0142300349.0...
5,The Cat in the Hat - The Movie,0.0,http://images.amazon.com/images/P/0375829016.0...
6,"The Lion, the Witch, and the Wardrobe (The Chr...",0.0,http://images.amazon.com/images/P/0064471047.0...
7,The SECRETS OF THE HEART : THE SECRETS OF THE ...,0.0,http://images.amazon.com/images/P/0671793411.0...
8,The Time of the Witch,0.0,http://images.amazon.com/images/P/0380711168.0...
9,"The Lion, the Witch, and the Wardrobe",0.0,http://images.amazon.com/images/P/0590254766.0...

In [32]:
book_to_search = "Pinocchio"
recommend_books = search_based_recommendation(book_to_search,df,tfidf,tfidf_matrix)
recommend_books

,Book-Title,Book-Rating,Image-URL-M
0,Pinocchio (Wordsworth Collection),8.0,http://images.amazon.com/images/P/1853261602.0...
1,Central Auditory Processing Disorders: New Per...,7.0,http://images.amazon.com/images/P/1565936973.0...
2,Fine Things,0.0,http://images.amazon.com/images/P/0440200563.0...
3,Amy and Isabelle,0.0,http://images.amazon.com/images/P/0684861593.0...
4,American Greats,10.0,http://images.amazon.com/images/P/1891620487.0...
5,Bleu presque transparent,0.0,http://images.amazon.com/images/P/2877302962.0...
6,A Coral Kiss,0.0,http://images.amazon.com/images/P/0446363499.0...
7,The Kid: What Happened After My Boyfriend and ...,0.0,http://images.amazon.com/images/P/0525945253.0...
8,The Monk Downstairs : A Novel,0.0,http://images.amazon.com/images/P/0062517864.0...
9,Fearless Living: Live Without Excuses and Love...,10.0,http://images.amazon.com/images/P/0525945792.0...

In [36]:
import pickle
with open("tfidf.pkl", "wb") as f:
    pickle.dump(tfidf, f)

In [37]:
with open("tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)

In [35]:
tfidf.vocabulary_

{'central': 2766,
 'auditory': 1458,
 'processing': 10613,
 'disorders': 4185,
 'new': 9358,
 'perspectives': 10137,
 'fine': 5325,
 'things': 13377,
 'amy': 1091,
 'and': 1112,
 'isabelle': 7185,
 'american': 1068,
 'greats': 6097,
 'bleu': 2042,
 'presque': 10548,
 'transparent': 13672,
 'coral': 3408,
 'kiss': 7572,
 'the': 13342,
 'kid': 7519,
 'what': 14575,
 'happened': 6310,
 'after': 867,
 'my': 9180,
 'boyfriend': 2223,
 'decided': 3856,
 'to': 13519,
 'go': 5973,
 'get': 5879,
 'pregnant': 10524,
 'an': 1093,
 'adoption': 820,
 'story': 12819,
 'monk': 8974,
 'downstairs': 4332,
 'novel': 9510,
 'fearless': 5191,
 'living': 8040,
 'live': 8035,
 'without': 14726,
 'excuses': 4977,
 'love': 8148,
 'regret': 11083,
 'still': 12776,
 'life': 7959,
 'with': 14722,
 'woodpecker': 14759,
 'yee': 14863,
 'haw': 6390,
 'fumblerules': 5670,
 'lighthearted': 7968,
 'guide': 6184,
 'grammar': 6056,
 'good': 6008,
 'usage': 14073,
 'magic': 8289,
 'journey': 7367,
 'riptide': 11329,
 'los': 8127,
 'cinco': 2976,
 'en': 4704,
 'el': 4606,
 'paramo': 9942,
 'misterioso': 8899,
 'five': 5375,
 'mystery': 9188,
 'moor': 9018,
 'in': 6950,
 'her': 6507,
 'shoes': 12122,
 'sky': 12303,
 'blues': 2093,
 'shoeless': 12121,
 'joe': 7338,
 'over': 9814,
 'edge': 4551,
 'man': 8364,
 'called': 2508,
 'peter': 10152,
 'of': 9619,
 'marshall': 8477,
 'galileo': 5721,
 'commandment': 3211,
 'anthology': 1200,
 'great': 6093,
 'science': 11778,
 'writing': 14809,
 'daughters': 3801,
 'sout': 12513,
 'wi': 14611,
 'if': 6881,
 'should': 12146,
 'die': 4089,
 'fountainhead': 5553,
 'segunda': 11893,
 'antologia': 1209,
 'poetica': 10358,
 '1898': 219,
 '1918': 224,
 'fiction': 5270,
 'poetry': 10359,
 'drama': 4360,
 'open': 9686,
 'joseph': 7357,
 'campbell': 2533,
 'conversation': 3376,
 'michael': 8772,
 'toms': 13561,
 'echine': 4531,
 'adversaire': 834,
 'yesterday': 14870,
 'forever': 5508,
 'time': 13484,
 'passages': 9985,
 'romance': 11405,
 'pressure': 10551,
 'points': 10365,
 'wish': 14711,
 'you': 14886,
 'well': 14528,
 'lion': 8007,
 'house': 6770,
 'recipes': 11008,
 'first': 5356,
 'edition': 4558,
 'leadership': 7801,
 'wisdom': 14708,
 'from': 5639,
 'who': 14603,
 'sold': 12440,
 'his': 6606,
 'ferrari': 5243,
 'rituals': 11341,
 'visionary': 14303,
 'leaders': 7800,
 'coitadinhos': 3137,
 'malandrãµes': 8334,
 'flagrantes': 5380,
 'do': 4228,
 'fim': 5310,
 'de': 3817,
 'feira': 5213,
 'brasil': 2249,
 'fhc': 5260,
 '1o': 276,
 '2o': 365,
 'crossing': 3585,
 'avalon': 1513,
 'woman': 14746,
 'midlife': 8793,
 'pilgrimage': 10256,
 'falcon': 5103,
 'flower': 5445,
 'canterbury': 2568,
 'tales': 13139,
 'modern': 8934,
 'english': 4758,
 'trouble': 13776,
 'teachers': 13220,
 'angela': 1133,
 'anaconda': 1095,
 'idiom': 6876,
 'delight': 3915,
 'fascinating': 5153,
 'phrases': 10200,
 'linguistic': 8002,
 'eccentricities': 4527,
 'spanish': 12536,
 'french': 5609,
 'italian': 7209,
 'latin': 7762,
 'testament': 13312,
 'treasures': 13708,
 'lost': 8136,
 'found': 5548,
 'silhoutte': 12211,
 'intimate': 7118,
 'moments': 8954,
 'carolina': 2631,
 'moon': 9007,
 'place': 10290,
 'come': 3196,
 'home': 6677,
 'carlson': 2621,
 'melody': 8669,
 'whispering': 14592,
 'pines': 10267,
 'series': 11969,
 'help': 6487,
 'laughing': 7767,
 'can': 2539,
 'up': 14052,
 'fall': 5104,
 'down': 4326,
 'funny': 5682,
 'stories': 12811,
 'fill': 5301,
 'your': 14889,
 'heart': 6427,
 'lift': 7965,
 'spirit': 12606,
 'startide': 12725,
 'rising': 11333,
 'uplift': 14056,
 'saga': 11581,
 'book': 2156,
 'blind': 2047,
 'assassin': 1397,
 'secret': 11859,
 'fear': 5190,
 'street': 12855,
 'end': 4723,
 'alice': 983,
 'god': 5978,
 'emperor': 4692,
 'dune': 4461,
 'chronicles': 2959,
 'forgotten': 5519,
 'island': 7192,
 'greenwitch': 6111,
 'under': 13931,
 'mistletoe': 8900,
 'rosie': 11446,
 'roses': 11443,
 'girls': 5926,
 'hunting': 6821,
 'fishing': 5367,
 'answered': 1193,
 'prayers': 10511,
 'beowulf': 1879,
 'verse': 14210,
 'translation': 13670,
 'sanctuary': 11634,
 'birth': 1983,
 'harlequin': 6333,
 'superromance': 12992,
 'one': 9668,
 'unbelieveable': 13908,
 'silhouette': 12209,
 'no': 9439,
 '8993': 669,
 'light': 7966,
 'window': 14668,
 'mitford': 8912,
 'years': 14860,
 'music': 9163,
 'essential': 4880,
 'lewis': 7915,
 'petain': 10148,
 'crime': 3556,
 'full': 5666,
 'collaboration': 3149,
 'holocaust': 6673,
 'finbar': 5317,
 'hotel': 6760,
 'hunt': 6817,
 'wheel': 14579,
 'der': 3974,
 'zirkel': 14931,
 'echoes': 4533,
 'wayside': 14476,
 'school': 11756,
 'gets': 5881,
 'little': 8031,
 'stranger': 12837,
 'morning': 9045,
 'primer': 10575,
 'on': 9665,
 'decision': 3860,
 'making': 8331,
 'how': 6779,
 'decisions': 3861,
 'happen': 6309,
 'pulling': 10732,
 'own': 9835,
 'strings': 12868,
 'dynamic': 4487,
 'techniques': 13236,
 'for': 5494,
 'dealing': 3830,
 'other': 9777,
 'people': 10093,
 'as': 1372,
 'choose': 2935,
 'prime': 10574,
 'evil': 4952,
 'by': 2454,
 'masters': 8516,
 'horror': 6745,
 'another': 1189,
 'city': 2996,
 'not': 9490,
 'form': 5520,
 'memoir': 8676,
 'more': 9032,
 'valentine': 14105,
 '473': 478,
 'homo': 6703,
 'zapiens': 14900,
 'fools': 5487,
 'fortune': 5535,
 'dolphins': 4264,
 'pern': 10126,
 'dragonriders': 4354,
 'paperback': 9919,
 'walk': 14394,
 'remember': 11138,
 'saints': 11594,
 'sword': 13082,
 'tyrants': 13875,
 'kings': 7556,
 'bk': 2003,
 'jim': 7326,
 'fixx': 5377,
 'second': 11855,
 'running': 11522,
 'named': 9219,
 'dave': 3802,
 'triumph': 13760,
 'forgiveness': 5517,
 'coyotes': 3510,
 'town': 13617,
 'dogs': 4250,
 'earth': 4503,
 'environmental': 4796,
 'movement': 9099,
 'mrs': 9109,
 'pollifax': 10394,
 'innocent': 7042,
 'tourist': 13609,
 'big': 1944,
 'bird': 1976,
 'says': 11699,
 'game': 5732,
 'read': 10963,
 'play': 10312,
 'step': 12756,
 'into': 7122,
 'reading': 10966,
 'vox': 14359,
 'best': 1903,
 'friends': 5627,
 'whirlwind': 14588,
 'tyler': 13866,
 'cat': 2686,
 'curmudgeon': 3657,
 'old': 9641,
 'impetuous': 6931,
 'body': 2115,
 'getting': 5882,
 'anger': 1141,
 'control': 3368,
 'notebook': 9493,
 'skies': 12291,
 'someplace': 12464,
 'be': 1741,
 'flying': 5459,
 'newford': 9361,
 'docbook': 4232,
 'definitive': 3899,
 'reilly': 11092,
 'xml': 14843,
 'last': 7754,
 'precinct': 10516,
 'irresistible': 7178,
 'forces': 5498,
 'government': 6035,
 'why': 14610,
 'washington': 14441,
 'stopped': 12805,
 'working': 14771,
 'norwegian': 9483,
 'wood': 14757,
 'vintage': 14275,
 'international': 7102,
 'original': 9751,
 'fast': 5159,
 'food': 5481,
 'nation': 9255,
 'dark': 3773,
 'side': 12178,
 'all': 991,
 'meal': 8610,
 'together': 13534,
 'paris': 9952,
 'easy': 4517,
 'movie': 9103,
 'storybook': 12820,
 'level': 7910,
 'convenient': 3372,
 'marriage': 8466,
 'see': 11874,
 'face': 5063,
 'again': 876,
 'brave': 2253,
 'world': 14775,
 'bridget': 2298,
 'jones': 7353,
 'diary': 4075,
 'must': 9171,
 'this': 13391,
 'jambalaya': 7252,
 'natural': 9263,
 'personal': 10133,
 'charms': 2844,
 'practical': 10493,
 'elizabethan': 4646,
 'underworld': 13948,
 'terminal': 13291,
 'safe': 11579,
 'sweet': 13060,
 'land': 7709,
 'golden': 5998,
 'lies': 7956,
 'father': 5170,
 'factor': 5069,
 'women': 14748,
 'dare': 3769,
 '659': 563,
 'blowout': 2081,
 'sunset': 12971,
 'holiday': 6662,
 'cujo': 3634,
 'hecate': 6452,
 'cauldron': 2720,
 'death': 3836,
 'charlie': 2837,
 'st': 12663,
 'cloud': 3087,
 '101': 23,
 'dalmatians': 3728,
 'disney': 4180,
 'classic': 3018,
 'taming': 13155,
 'eliza': 4644,
 'road': 11353,
 'omaha': 9656,
 'catcher': 2696,
 'rye': 11546,
 'at': 1420,
 'odds': 9612,
 '3323': 398,
 'stupidest': 12899,
 'laws': 7785,
 'smallest': 12367,
 'cow': 3502,
 'penguin': 10078,
 'poets': 10360,
 'canticle': 2570,
 'leibowitz': 7852,
 'russia': 11528,
 'james': 7253,
 'bond': 2136,
 'older': 9642,
 'special': 12552,
 '1445': 124,
 'cardinal': 2605,
 'kremlin': 7648,
 'jack': 7229,
 'ryan': 11545,
 'novels': 9518,
 'rapture': 10922,
 'canaan': 2540,
 'kingmaker': 7554,
 'unknown': 14000,
 'animorphs': 1160,
 '14': 111,
 'green': 6102,
 'mile': 8815,
 'bad': 1590,
 'eduard': 4564,
 'delacroix': 3908,
 'final': 5311,
 'target': 13184,
 'ghost': 5887,
 'angel': 1132,
 'geschichte': 5871,
 'eines': 4596,
 'straã': 12851,
 'enkids': 4768,
 'desperation': 4009,
 'judgement': 7386,
 'midnight': 8794,
 'flight': 5421,
 'broken': 2329,
 'wings': 14682,
 'stuff': 12893,
 'communion': 3229,
 'are': 1312,
 'there': 13359,
 'it': 7207,
 'me': 8608,
 'margaret': 8422,
 'cold': 3140,
 'iron': 7174,
 'patty': 10020,
 'jane': 7257,
 'curl': 3656,
 'mortal': 9056,
 'remains': 11135,
 'stalker': 12683,
 'affair': 847,
 'merry': 8733,
 'christmas': 2951,
 'mom': 8952,
 'dad': 3704,
 'look': 8101,
 'mary': 8495,
 'queen': 10786,
 'scots': 11797,
 'murder': 9147,
 'lord': 8117,
 'darnley': 3786,
 '12': 71,
 'weeks': 14504,
 'mental': 8701,
 'physical': 10203,
 'strength': 12858,
 'solomon': 12450,
 'spring': 12636,
 'eden': 4549,
 'murdoch': 9153,
 'lawman': 7782,
 'surrender': 13020,
 'felidae': 5218,
 'roman': 11404,
 'country': 3478,
 'writings': 14810,
 'about': 730,
 'rural': 11525,
 'canada': 2541,
 'hope': 6728,
 'jar': 7272,
 'america': 1067,
 'beauty': 1774,
 'culture': 3641,
 'lick': 7943,
 'sugar': 12937,
 'habit': 6233,
 'dragonflight': 4349,
 'trilogy': 13751,
 'family': 5119,
 'orchard': 9723,
 'torn': 13586,
 'away': 1540,
 'nothing': 9498,
 'lasts': 7757,
 'timeline': 13486,
 'balzac': 1637,
 'et': 4895,
 'la': 7680,
 'petite': 10157,
 'tailleuse': 13123,
 'chino': 2918,
 'dance': 3744,
 'upon': 14057,
 'air': 916,
 'three': 13413,
 'sisters': 12265,
 'fried': 5624,
 'tomatoes': 13552,
 'whistle': 14594,
 'stop': 12804,
 'cafe': 2479,
 'pretty': 10559,
 'horses': 6753,
 'border': 2175,
 'vol': 14339,
 'satan': 11670,
 'instruction': 7077,
 'diamond': 4068,
 'dust': 4477,
 'cry': 3612,
 'beloved': 1863,
 'mercy': 8717,
 'seven': 11991,
 'habits': 6235,
 'highly': 6573,
 'effective': 4573,
 'aunt': 1469,
 'dimity': 4123,
 'art': 1358,
 'du': 4430,
 'voyage': 14360,
 'un': 13899,
 'regard': 11068,
 'plutã': 10343,
 'politique': 10390,
 'sur': 13008,
 'autre': 1506,
 'ailleurs': 908,
 'haunting': 6379,
 'grade': 6043,
 'lucky': 8187,
 'star': 12700,
 'macbest': 8232,
 'fantasy': 5140,
 'men': 8689,
 'kilts': 7537,
 'australian': 1483,
 'slanguage': 12319,
 'we': 14478,
 'say': 11696,
 'surrounded': 13022,
 'strangers': 12838,
 'berkley': 1887,
 'sensation': 11933,
 'just': 7426,
 'am': 1042,
 'lady': 7693,
 'question': 10796,
 'true': 13787,
 'make': 8324,
 'relationship': 11109,
 'sweeter': 13061,
 'deeper': 3882,
 'passionate': 9991,
 'boss': 2190,
 'arrival': 1351,
 'survival': 13025,
 'plan': 10298,
 'magnificat': 8300,
 'galactic': 5711,
 'milieu': 8819,
 'comanche': 3192,
 'lonesome': 8094,
 'dove': 4323,
 'horse': 6749,
 'whisperer': 14591,
 'so': 12408,
 'universe': 13994,
 'marketing': 8450,
 'based': 1696,
 'business': 2435,
 'cider': 2970,
 'rules': 11504,
 'whispers': 14593,
 'intrigue': 7126,
 '236': 321,
 'opposing': 9702,
 'viewpoints': 14253,
 'history': 6620,
 'comment': 3213,
 'voyager': 14361,
 'avec': 1518,
 'saumon': 11680,
 'nouveaux': 9507,
 'pastiches': 9997,
 'postiches': 10457,
 'retro': 11230,
 'lives': 8037,
 'fire': 5340,
 'engine': 4752,
 'rescue': 11188,
 'storytime': 12823,
 'books': 2162,
 'karen': 7459,
 'picture': 10225,
 'baby': 1568,
 'sitters': 12269,
 'sister': 12262,
 'mcnally': 8601,
 'puzzle': 10758,
 'archy': 1307,
 'taking': 13133,
 'poisonwood': 10369,
 'bible': 1933,
 'night': 9402,
 'crew': 3552,
 'al': 940,
 'capone': 2584,
 'does': 4243,
 'shirts': 12114,
 'firstborn': 5357,
 'dragonlance': 4353,
 'elven': 4669,
 'nations': 9259,
 'rancher': 10903,
 'runaway': 11513,
 'bride': 2292,
 'glory': 5961,
 'super': 12974,
 '739': 597,
 'finally': 5312,
 'doctor': 4235,
 'wild': 14632,
 'crusaders': 3606,
 'curmudgeons': 3658,
 'completely': 3254,
 'corsetless': 3445,
 'ladies': 7692,
 'otherwise': 9781,
 'virtuous': 14294,
 'victorian': 14238,
 'era': 4817,
 'darkness': 3780,
 'italia': 7208,
 'orchids': 9726,
 'paradise': 9935,
 'county': 3479,
 'snack': 12387,
 'thief': 13370,
 'inspector': 7062,
 'montalbano': 8986,
 'mysteries': 9186,
 'alienist': 986,
 'approaches': 1262,
 'cancer': 2547,
 'everyone': 4946,
 'needs': 9308,
 'know': 7608,
 'orthodox': 9763,
 'complementary': 3252,
 'methods': 8757,
 'prevention': 10561,
 'treatment': 13711,
 'cure': 3651,
 'charming': 2843,
 'prince': 10581,
 'heir': 6467,
 'empire': 4695,
 'wars': 14434,
 'blue': 2087,
 'bayou': 1732,
 'haunted': 6378,
 'mesa': 8738,
 'mother': 9073,
 'tale': 13136,
 'did': 4085,
 'tara': 13180,
 'paxton': 10032,
 'cheerleaders': 2869,
 'gave': 5776,
 'them': 13347,
 'advanced': 827,
 'pendulum': 10077,
 'applications': 1255,
 'knowing': 7610,
 'intuitive': 7135,
 'mind': 8834,
 'widows': 14622,
 'broome': 2335,
 'pioneers': 10271,
 'unseen': 14022,
 'frontiers': 5645,
 'too': 13572,
 'close': 3077,
 'falls': 5109,
 'judgment': 7387,
 'calls': 2511,
 'ecopolitics': 4544,
 'building': 2388,
 'society': 12420,
 'imperfect': 6927,
 've': 14140,
 'been': 1798,
 'gone': 6007,
 'far': 5142,
 'long': 8095,
 'field': 5275,
 'study': 12892,
 'fiascoes': 5266,
 'expedition': 5008,
 'disasters': 4155,
 'travel': 13687,
 'literature': 8030,
 'chosen': 2941,
 'prey': 10562,
 'zodiac': 14937,
 'club': 3092,
 'mira': 8870,
 'criminal': 3558,
 'justice': 7427,
 'encore': 4715,
 'immaculate': 6918,
 'deception': 3855,
 'short': 12138,
 'girl': 5921,
 'swing': 13075,
 'whatever': 14576,
 'means': 8615,
 'missing': 8891,
 'susan': 13032,
 'stroke': 12874,
 'madness': 8269,
 'agente': 885,
 'confidencial': 3295,
 'confidential': 3297,
 'agent': 884,
 'pug': 10728,
 'shots': 12145,
 'icebergs': 6857,
 'facts': 5073,
 'activities': 791,
 'ridge': 11300,
 'epic': 4801,
 'army': 1341,
 '10th': 48,
 'mountain': 9088,
 'division': 4219,
 'assault': 1401,
 'hitler': 6631,
 'europe': 4917,
 'saint': 11593,
 'maybe': 8564,
 'till': 13477,
 'have': 6387,
 'faces': 5065,
 'myth': 9195,
 'retold': 11226,
 'human': 6799,
 'stain': 12674,
 'came': 2519,
 'victim': 14235,
 'free': 5594,
 'crimson': 3561,
 'chromosome': 2955,
 'martian': 8482,
 'trixie': 13763,
 'belden': 1837,
 'off': 9620,
 'glen': 5944,
 'kashmir': 7469,
 'disclosure': 4158,
 'neuromancer': 9351,
 'remembering': 11140,
 'tomorrow': 13558,
 'poems': 10352,
 'capital': 2579,
 'punishment': 10737,
 'andromeda': 1125,
 'strain': 12829,
 'talk': 13143,
 'day': 3808,
 'child': 2900,
 'year': 14857,
 'celebrations': 2750,
 'hundreds': 6813,
 'ideas': 6871,
 'amp': 1087,
 'fun': 5671,
 'elroy': 4662,
 'nights': 9411,
 'class': 3016,
 'reunion': 11238,
 'complete': 3253,
 'twentieth': 13850,
 'century': 2771,
 'classics': 3020,
 'phantom': 10170,
 'opera': 9690,
 'encyclopedia': 4722,
 'brown': 2341,
 'sets': 11988,
 'pace': 9850,
 'isle': 7195,
 'mythic': 9197,
 'forest': 5505,
 'high': 6569,
 'maintenance': 8317,
 'angels': 1140,
 'our': 9789,
 'midst': 8795,
 'lammas': 7704,
 'dreamcatcher': 4374,
 'escape': 4849,
 'next': 9369,
 'accident': 756,
 'guests': 6181,
 'sheik': 12079,
 'ethnography': 4903,
 'iraqi': 7168,
 'village': 14262,
 'fiber': 5267,
 'expressions': 5036,
 'knotting': 7607,
 'looping': 8112,
 'confucio': 3301,
 'nel': 9321,
 'computer': 3267,
 'memoria': 8680,
 'accidentale': 758,
 'del': 3907,
 'futuro': 5692,
 'anne': 1173,
 'frank': 5575,
 'young': 14887,
 'cthulhu': 3623,
 'mythos': 9200,
 'ghosts': 5891,
 'supernatural': 12990,
 'thriller': 13417,
 'wall': 14399,
 'loop': 8111,
 'card': 2603,
 'games': 5734,
 'glitter': 5950,
 'gold': 5996,
 'shake': 12032,
 'hands': 6290,
 'twist': 13858,
 'idiot': 6877,
 'oxford': 9841,
 'oscar': 9769,
 'lucinda': 8184,
 'oz': 9846,
 'backpacker': 1580,
 'problem': 10607,
 'solving': 12457,
 'manual': 8401,
 'use': 14075,
 'wilds': 14642,
 'enchantments': 4713,
 'flesh': 5411,
 'wraeththu': 14796,
 'two': 13862,
 'part': 9968,
 'invention': 7143,
 'crosswicks': 3589,
 'journal': 7364,
 'thunder': 13433,
 'lightning': 7972,
 'cracking': 3513,
 'writer': 14806,
 'craft': 3516,
 'dial': 4063,
 'don': 4277,
 'she': 12076,
 'kate': 7474,
 'reddy': 11032,
 'unicorn': 13977,
 'regulators': 11085,
 'psycho': 10706,
 'ii': 6889,
 'robert': 11363,
 'bloch': 2053,
 'couldn': 3466,
 'keep': 7488,
 'myself': 9184,
 'testimonies': 13316,
 'imprisoned': 6942,
 'pelican': 10067,
 'brief': 2300,
 'princess': 10583,
 'sultana': 12950,
 'circle': 2986,
 'may': 8561,
 'tie': 13456,
 'alligator': 1006,
 'hydrant': 6836,
 'real': 10971,
 'dumb': 4455,
 'david': 3803,
 'copperfield': 3404,
 'signet': 12198,
 'autobiography': 1497,
 'toklas': 13542,
 'library': 7934,
 'hardcover': 6324,
 'king': 7551,
 'rat': 10926,
 'literary': 8028,
 'amherst': 1074,
 'clan': 3009,
 'cave': 2728,
 'bear': 1757,
 'children': 2905,
 'celestine': 2753,
 'prophecy': 10654,
 'memoirs': 8678,
 'cleopatra': 3045,
 'geheimnisse': 5804,
 'zwischen': 14967,
 'liebenden': 7949,
 'hearts': 6437,
 'flowers': 5447,
 '425': 458,
 'curious': 3655,
 'incident': 6960,
 'dog': 4245,
 'indecent': 6973,
 'obsession': 9592,
 'paper': 9918,
 'parables': 9928,
 'peanuts': 10050,
 'tibet': 13445,
 'markets': 8451,
 'education': 4566,
 'studies': 12891,
 'penguins': 10079,
 'knees': 7595,
 'red': 11030,
 'thought': 13404,
 'inspired': 7068,
 'moonlight': 9011,
 'middle': 8788,
 'thousand': 13406,
 'days': 3812,
 'venice': 14164,
 'unexpected': 13959,
 ...}